
package cn.yxd.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "test1", targetNamespace = "http://test.yxd.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Test1 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test.yxd.cn/", className = "cn.yxd.test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.yxd.cn/", className = "cn.yxd.test.SayHelloResponse")
    @Action(input = "http://test.yxd.cn/test1/sayHelloRequest", output = "http://test.yxd.cn/test1/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

}
